In [1]:
#Q. 1.Write a code to combine  a one and a two-dimensional NumPy Array
import numpy as np
print("1 Dimension Array: ")
ar1=np.arange(7)
print(ar1)

print("\n 2 Dimension Array: ")
ar2=np.arange(21).reshape(3,7)
print(ar2)
for a,b in np.nditer([ar1,ar2]):
    print("%d : %d"%(a,b))

1 Dimension Array: 
[0 1 2 3 4 5 6]

 2 Dimension Array: 
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]
0 : 0
1 : 1
2 : 2
3 : 3
4 : 4
5 : 5
6 : 6
0 : 7
1 : 8
2 : 9
3 : 10
4 : 11
5 : 12
6 : 13
0 : 14
1 : 15
2 : 16
3 : 17
4 : 18
5 : 19
6 : 20


In [2]:
#Q. 2. Write a code to check whether a Numpy array contains a specified row. 
import numpy as np
arr=np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20]
                   ])
print(arr)
print([1,2,3,4,5] in arr.tolist())
print([1,-2,5,4,-8] in arr.tolist())
print([11,12,13,14,15] in arr.tolist())
print([16,17,18,19,20,21] in arr.tolist())

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
True
False


In [3]:
#Q. 3.  Write a Pandas code to create and display a DataFrame from a specified dictionary data which has the index labels

import pandas as pd
exam_date={'name':['sam','ravi','raj','sunny','ram'],
          'attempts':[1,2,3.,2,1],
          'score':[8,12,9,12,19],
          'qualify':['no','yes','no','yes','yes']}
label=['a','b','c','d','e']
df=pd.DataFrame(exam_date,index=label)
print(df)

    name  attempts  score qualify
a    sam       1.0      8      no
b   ravi       2.0     12     yes
c    raj       3.0      9      no
d  sunny       2.0     12     yes
e    ram       1.0     19     yes


In [4]:
#Q. 4.Write a pandas code to create DataFrame from dict of narray/lists

import pandas as pd
data={'name':['sam','ram','amit'],
     'marks':[85,95,75]}
df=pd.DataFrame(data)
print(df)

   name  marks
0   sam     85
1   ram     95
2  amit     75


In [7]:
#Q. 5. Write a pandas code to create Pandas dataframe using list of lists

import pandas as pd
data=[['sam',20],['ravi',25],['amit',21]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)


   Name  Age
0   sam   20
1  ravi   25
2  amit   21
